%%{init: {"themeVariables": {"fontSize": "14px"}} }%%
xychart-beta
    title "Latência média — Sign e Verify (Service Layer)"
    x-axis ["jwt_sign (RS256)", "pqc_sign (ML-DSA-44)", "jwt_verify (RS256)", "pqc_verify (ML-DSA-44)"]
    y-axis "Latência (ms)" 0 --> 2
    bar [1.629, 0.203, 0.058, 0.044]
